export const mockNews = [
	{
		id: "1",
		title: "Breaking News: React 19 Released!",
		published: new Date().toISOString(),
		author: "OpenAI Reporter",
		image: "https://picsum.photos/seed/news1/800/400",
		category: "react",
	},
	{
		id: "2",
		title: "Frontend Trends of 2025",
		published: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
		author: "Tech Guru",
		image: "https://picsum.photos/seed/news2/800/400",
		category: "frontend",
	},
	{
		id: "3",
		title: "AI Revolutionizes Web Development",
		published: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
		author: "AI Times",
		image: "https://picsum.photos/seed/news3/800/400",
		category: "ai",
	},
	{
		id: "4",
		title: "JavaScript: Still King in 2025",
		published: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
		author: "JS Daily",
		image: "https://picsum.photos/seed/news4/800/400",
		category: "javascript",
	},
	{
		id: "5",
		title: "CSS4 Coming Soon: What We Know",
		published: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
		author: "Design Weekly",
		image: "https://picsum.photos/seed/news5/800/400",
		category: "css",
	},
	{
		id: "6",
		title: "Why TypeScript Is a Must in 2025",
		published: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
		author: "Code World",
		image: "https://picsum.photos/seed/news6/800/400",
		category: "typescript",
	},
	{
		id: "7",
		title: "WebAssembly Adoption on the Rise",
		published: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
		author: "DevTech",
		image: "https://picsum.photos/seed/news7/800/400",
		category: "webassembly",
	},
	{
		id: "8",
		title: "10 VS Code Extensions You Need",
		published: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
		author: "Editor Tips",
		image: "https://picsum.photos/seed/news8/800/400",
		category: "tools",
	},
	{
		id: "9",
		title: "How to Build a Design System",
		published: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
		author: "UX Masters",
		image: "https://picsum.photos/seed/news9/800/400",
		category: "design",
	},
	{
		id: "10",
		title: "Next.js vs Remix: 2025 Comparison",
		published: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
		author: "React Weekly",
		image: "https://picsum.photos/seed/news10/800/400",
		category: "react",
	},
	{
		id: "11",
		title: "Svelte 5: Lighter and Faster",
		published: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
		author: "Frontend Lab",
		image: "https://picsum.photos/seed/news11/800/400",
		category: "svelte",
	},
	{
		id: "12",
		title: "Top UI Frameworks in 2025",
		published: new Date(Date.now() - 1000 * 60 * 60 * 45).toISOString(),
		author: "Design Journal",
		image: "https://picsum.photos/seed/news12/800/400",
		category: "frontend",
	},
	{
		id: "13",
		title: "Best Practices for Web Security",
		published: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
		author: "CyberSafe",
		image: "https://picsum.photos/seed/news13/800/400",
		category: "security",
	},
	{
		id: "14",
		title: "Optimizing Performance with React",
		published: new Date(Date.now() - 1000 * 60 * 60 * 55).toISOString(),
		author: "React Pros",
		image: "https://picsum.photos/seed/news14/800/400",
		category: "react",
	},
	{
		id: "15",
		title: "Serverless in 2025: What to Expect",
		published: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
		author: "Cloud Devs",
		image: "https://picsum.photos/seed/news15/800/400",
		category: "cloud",
	},
	{
		id: "16",
		title: "Dark Mode UX: Pros and Cons",
		published: new Date(Date.now() - 1000 * 60 * 60 * 65).toISOString(),
		author: "UX Guide",
		image: "https://picsum.photos/seed/news16/800/400",
		category: "ux",
	},
	{
		id: "17",
		title: "Learning Rust as a JS Developer",
		published: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
		author: "Dev Journal",
		image: "https://picsum.photos/seed/news17/800/400",
		category: "rust",
	},
	{
		id: "18",
		title: "Why Everyone's Using Tailwind CSS",
		published: new Date(Date.now() - 1000 * 60 * 60 * 75).toISOString(),
		author: "CSS Today",
		image: "https://picsum.photos/seed/news18/800/400",
		category: "css",
	},
	{
		id: "19",
		title: "Top Mistakes in React Apps",
		published: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
		author: "BugSquashers",
		image: "https://picsum.photos/seed/news19/800/400",
		category: "react",
	},
	{
		id: "20",
		title: "The Rise of Edge Computing",
		published: new Date(Date.now() - 1000 * 60 * 60 * 85).toISOString(),
		author: "Tech World",
		image: "https://picsum.photos/seed/news20/800/400",
		category: "cloud",
	},
];
